require("samisdat.plugins-setup")

require("samisdat.core.options")
require("samisdat.core.keymaps")
require("samisdat.core.colorscheme")
require("samisdat.plugins.comment")
require("samisdat.plugins.nvim-tree")
require("samisdat.plugins.lualine")
require("samisdat.plugins.telescope")
require("samisdat.plugins.nvim-cmp")
require("samisdat.plugins.autopairs")
require("samisdat.plugins.treesitter")
require("samisdat.plugins.gitsigns")
